# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='food',
        ),
        migrations.RemoveField(
            model_name='food',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='recipeline',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Food'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_lines',
            field=models.ManyToManyField(through='polls.RecipeLine', to='polls.Food'),
        ),
    ]
